## Build Speech data files

In [46]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import MinMaxScaler
from IPython.display import display

%matplotlib inline

kode ini merubah dari 7 kelas emosi menjadi 5 kelas emosi

In [47]:
df = pd.read_csv('data/pre-processed/audio_features.csv')
df = df[df['label'].isin([0, 1, 2, 3, 4, 5, 6, 7])]
print(df.shape)
display(df.head())

# change 7 to 2
df['label'] = df['label'].map({0: 0, 1: 1, 2: 1, 3: 2, 4: 2, 5: 3, 6: 4, 7: 5})
df.head()

(1402, 10)


wav_file  label  sig_mean   sig_std  rmse_mean  rmse_std  \
0  Ses01F_impro01_F000      7  0.004029  0.007451   0.005045  0.005466   
1  Ses01F_impro01_F001      7  0.004209  0.009823   0.005309  0.008218   
2  Ses01F_impro01_F002      7  0.003928  0.007829   0.004941  0.006064   
5  Ses01F_impro01_F005      7  0.030085  0.054550   0.037255  0.039751   
6  Ses01F_impro01_F006      4  0.046330  0.074601   0.056799  0.048212   

    silence  harmonic  auto_corr_max  auto_corr_std  
0  0.125000 -0.007787       0.043667       0.165918  
1  0.491667 -0.006072       0.083406       0.160758  
2  0.385185 -0.010218       0.049978       0.112936  
5  0.428161 -0.005372       2.280359       7.328892  
6  0.255639 -0.009276       3.977544      21.287299

wav_file  label  sig_mean   sig_std  rmse_mean  rmse_std  \
0  Ses01F_impro01_F000      5  0.004029  0.007451   0.005045  0.005466   
1  Ses01F_impro01_F001      5  0.004209  0.009823   0.005309  0.008218   
2  Ses01F_impro01_F002      5  0.003928  0.007829   0.004941  0.006064   
5  Ses01F_impro01_F005      5  0.030085  0.054550   0.037255  0.039751   
6  Ses01F_impro01_F006      2  0.046330  0.074601   0.056799  0.048212   

    silence  harmonic  auto_corr_max  auto_corr_std  
0  0.125000 -0.007787       0.043667       0.165918  
1  0.491667 -0.006072       0.083406       0.160758  
2  0.385185 -0.010218       0.049978       0.112936  
5  0.428161 -0.005372       2.280359       7.328892  
6  0.255639 -0.009276       3.977544      21.287299

In [62]:
print(dict(pd.Series(df['label']).value_counts()))

{2: 474, 5: 384, 1: 278, 0: 229, 4: 25, 3: 12}


In [48]:
df.to_csv('data/no_sample_df.csv')

# oversample fear
# Oversample fear class (label == 3)
fear_df = df[df['label'] == 3]

# Buat list DataFrame yang berisi data asli dan 30 kali duplikasi fear_df
dfs_to_concat = [df] + [fear_df] * 30

# Gabungkan semua DataFrame sekaligus
df_oversampled = pd.concat(dfs_to_concat, ignore_index=True)

sur_df = df[df['label'] == 4]
dfs_to_concat.extend([sur_df] * 10)
df_oversampled = pd.concat(dfs_to_concat, ignore_index=True)



df.to_csv('data/modified_df.csv')
df.head()
df.tail()

wav_file  label  sig_mean   sig_std  rmse_mean  rmse_std  \
1813  Ses01M_script03_2_M039      0  0.053390  0.085045   0.064859  0.054324   
1814  Ses01M_script03_2_M040      0  0.135510  0.212167   0.165673  0.132512   
1815  Ses01M_script03_2_M041      0  0.012510  0.024618   0.015979  0.018375   
1816  Ses01M_script03_2_M042      0  0.054021  0.090460   0.068241  0.058177   
1817  Ses01M_script03_2_M043      0  0.285385  0.376505   0.346450  0.147194   

       silence  harmonic  auto_corr_max  auto_corr_std  
1813  0.304813 -0.021451       5.102758      12.579419  
1814  0.301685  0.443895      31.220680      80.526581  
1815  0.464646 -0.005501       0.488538       0.901831  
1816  0.201342 -0.003402       6.049263       8.901351  
1817  0.102606  4.239072      82.642290     282.905101

In [49]:
df.head()

wav_file  label  sig_mean   sig_std  rmse_mean  rmse_std  \
0  Ses01F_impro01_F000      5  0.004029  0.007451   0.005045  0.005466   
1  Ses01F_impro01_F001      5  0.004209  0.009823   0.005309  0.008218   
2  Ses01F_impro01_F002      5  0.003928  0.007829   0.004941  0.006064   
5  Ses01F_impro01_F005      5  0.030085  0.054550   0.037255  0.039751   
6  Ses01F_impro01_F006      2  0.046330  0.074601   0.056799  0.048212   

    silence  harmonic  auto_corr_max  auto_corr_std  
0  0.125000 -0.007787       0.043667       0.165918  
1  0.491667 -0.006072       0.083406       0.160758  
2  0.385185 -0.010218       0.049978       0.112936  
5  0.428161 -0.005372       2.280359       7.328892  
6  0.255639 -0.009276       3.977544      21.287299

In [50]:
df.tail()

wav_file  label  sig_mean   sig_std  rmse_mean  rmse_std  \
1813  Ses01M_script03_2_M039      0  0.053390  0.085045   0.064859  0.054324   
1814  Ses01M_script03_2_M040      0  0.135510  0.212167   0.165673  0.132512   
1815  Ses01M_script03_2_M041      0  0.012510  0.024618   0.015979  0.018375   
1816  Ses01M_script03_2_M042      0  0.054021  0.090460   0.068241  0.058177   
1817  Ses01M_script03_2_M043      0  0.285385  0.376505   0.346450  0.147194   

       silence  harmonic  auto_corr_max  auto_corr_std  
1813  0.304813 -0.021451       5.102758      12.579419  
1814  0.301685  0.443895      31.220680      80.526581  
1815  0.464646 -0.005501       0.488538       0.901831  
1816  0.201342 -0.003402       6.049263       8.901351  
1817  0.102606  4.239072      82.642290     282.905101

In [51]:

unique_values = df['label'].unique()
print(unique_values)


[5 2 0 1 4 3]


In [52]:
import numpy as np

# Ambil 5 data pertama
first_five =  df.head(5)

# Nilai minimal dan maksimal per kolom
min_vals = np.min(first_five, axis=0)
max_vals = np.max(first_five, axis=0)

print("Nilai minimal per kolom pada 5 data pertama:", min_vals)
print("Nilai maksimal per kolom pada 5 data pertama:", max_vals)


Nilai minimal per kolom pada 5 data pertama: wav_file         Ses01F_impro01_F000
label                              2
sig_mean                    0.003928
sig_std                     0.007451
rmse_mean                   0.004941
rmse_std                    0.005466
silence                        0.125
harmonic                   -0.010218
auto_corr_max               0.043667
auto_corr_std               0.112936
dtype: object
Nilai maksimal per kolom pada 5 data pertama: wav_file         Ses01F_impro01_F006
label                              5
sig_mean                     0.04633
sig_std                     0.074601
rmse_mean                   0.056799
rmse_std                    0.048212
silence                     0.491667
harmonic                   -0.005372
auto_corr_max               3.977544
auto_corr_std              21.287299
dtype: object


In [53]:

unique_values = df['label'].unique()
print(unique_values)


[5 2 0 1 4 3]


In [54]:
import numpy as np
df = pd.read_csv('data/modified_df.csv')

emotion_dict = {'ang': 0,
                'hap': 1,
                'sad': 2,
                'neu': 3,}

# emotion_dict = {'ang': 0,
#                 'hap': 1,
#                 'exc': 2,
#                 'sad': 3,
#                 'fru': 4,
#                 'fea': 5,
#                 'sur': 6,
#                 'neu': 7,
#                 'xxx': 8,
#                 'oth': 8}


scalar = MinMaxScaler()
df[df.columns[3:]] = scalar.fit_transform(df[df.columns[3:]])
df.head()

Unnamed: 0             wav_file  label  sig_mean   sig_std  rmse_mean  \
0           0  Ses01F_impro01_F000      5  0.008218  0.014212   0.008571   
1           1  Ses01F_impro01_F001      5  0.008853  0.020548   0.009339   
2           2  Ses01F_impro01_F002      5  0.007861  0.015221   0.008268   
3           5  Ses01F_impro01_F005      5  0.100066  0.140018   0.102109   
4           6  Ses01F_impro01_F006      2  0.157329  0.193577   0.158861   

   rmse_std   silence  harmonic  auto_corr_max  auto_corr_std  
0  0.028135  0.166244  0.171332       0.000498       0.000563  
1  0.043256  0.653892  0.171667       0.000979       0.000545  
2  0.031424  0.512277  0.170858       0.000575       0.000376  
3  0.216499  0.569432  0.171803       0.027564       0.025883  
4  0.262985  0.339987  0.171042       0.048101       0.075224

In [55]:

unique_values = df['label'].unique()
print(unique_values)

unique_count = df['label'].nunique()
print(f"Jumlah nilai unik di kolom 'nama_kolom': {unique_count}")



[5 2 0 1 4 3]
Jumlah nilai unik di kolom 'nama_kolom': 6


In [56]:
x_train, x_test = train_test_split(df, test_size=0.20)

x_train.to_csv('data/s2e/audio_train.csv', index=False)
x_test.to_csv('data/s2e/audio_test.csv', index=False)

print(x_train.shape, x_test.shape)

(1121, 11) (281, 11)


In [61]:
print(dict(pd.Series(x_train['label']).value_counts()))

{2: 377, 5: 311, 1: 221, 0: 185, 4: 19, 3: 8}


## Define preprocessing functions for text

In [57]:
import unicodedata

def unicodeToAscii(s):
    return ''.join(
        c for c in unicodedata.normalize('NFD', s)
        if unicodedata.category(c) != 'Mn'
    )

# Lowercase, trim, and remove non-letter characters
def normalizeString(s):
    s = unicodeToAscii(s.lower().strip())
    s = re.sub(r"([.!?])", r" \1", s)
    s = re.sub(r"[^a-zA-Z.!?]+", r" ", s)
    return s

## Build Text data files

In [58]:
import re
import os
import pickle

useful_regex = re.compile(r'^(\w+)', re.IGNORECASE)

file2transcriptions = {}

for sess in [1]:
    transcripts_path = 'data/IEMOCAP_full_release/Session{}/dialog/transcriptions/'.format(sess)
    transcript_files = os.listdir(transcripts_path)
    for f in transcript_files:
        with open('{}{}'.format(transcripts_path, f), 'r') as f:
            all_lines = f.readlines()

        for l in all_lines:
            audio_code = useful_regex.match(l).group()
            transcription = l.split(':')[-1].strip()
            # assuming that all the keys would be unique and hence no `try`
            file2transcriptions[audio_code] = transcription
# save dict
with open('data/t2e/audiocode2text.pkl', 'wb') as file:
    pickle.dump(file2transcriptions, file)
len(file2transcriptions)

1821

In [59]:
audiocode2text = pickle.load(open('data/t2e/audiocode2text.pkl', 'rb'))

In [60]:
# Prepare text data
text_train = pd.DataFrame()
text_train['wav_file'] = x_train['wav_file']
text_train['label'] = x_train['label']
text_train['transcription'] = [normalizeString(audiocode2text[code]) for code in x_train['wav_file']]

text_test = pd.DataFrame()
text_test['wav_file'] = x_test['wav_file']
text_test['label'] = x_test['label']
text_test['transcription'] = [normalizeString(audiocode2text[code]) for code in x_test['wav_file']]

text_train.to_csv('data/t2e/text_train.csv', index=False)
text_test.to_csv('data/t2e/text_test.csv', index=False)

print(text_train.shape, text_test.shape)

(1121, 3) (281, 3)
